### ISSUE TITLE
Dark Sky not working

### ISSUE THREAD

**Issue by DlljsCodes** [DlljsCodes/log-cabin-control-system#9]
The following error occurs:
```
Traceback (most recent call last):
  File "log_cabin_control_server.py", line 660, in <module>
    main()
  File "log_cabin_control_server.py", line 644, in main
    main_loop()
  File "log_cabin_control_server.py", line 112, in main_loop
    blinds()   # Blinds Module
  File "log_cabin_control_server.py", line 207, in blinds
    blinds_morning()  # Will close blinds if successful
  File "log_cabin_control_server.py", line 226, in blinds_morning
    cloud_cover = forecast.daily.data_class.cloud_cover
AttributeError: type object 'DailyForecastItem' has no attribute 'cloud_cover'
```
Potential fix is to change `forecast.daily.data_class.cloud_cover` to `forecast.daily.data[0].cloud_cover` instead. See Detrous/darksky#13 & Detrous/darksky#23.

**Comment by DlljsCodes** [comment]
Fix confirmed working
